version: '3'
services:
  game1:
    build: .
    container_name: 2048-game-1
    restart: always
    ports:
      - '9000:8080'
  game2:
    build: .
    container_name: 2048-game-2
    restart: always
    ports:
      - '9001:8080'